<a href="https://colab.research.google.com/github/Alishabohara-07/Machine-Learning/blob/main/iIntroduction_ML_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Numpy

What will we cover?

 Creating arrays

 Multi dimensional array
 Rnadomly generated arrays
 Element wise operators


           Comparision operations
           Logical Operations

           Summarizing Operations

```
# This is formatted as code
```



In [2]:
import numpy as np

Creating Arrays

In [4]:
 var = np.zeros(5)
 print(type(var))


<class 'numpy.ndarray'>


In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [8]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [10]:
var = np.array([1, 2, 3, 4])
var[2] = 6
print(var)

[1 2 6 4]


In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

create arrays with evenly  spaced numbers within a specified range

In [13]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

###Multidimensional Arrays

In [14]:
# creating an MD unit Array of size (5,2)
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:

#Generate a random array of size (3, 5) with elements of your choice

# zero_array = np.zeros((5, 2))
# random_array = np.random.randint(1, 11, (3, 5))


# print("\nRandom Array (3,5):")
# print(random_array)

n= np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6],
    [6, 7, 8, 9, 0]
])
n


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [6, 7, 8, 9, 0]])

In [24]:
#update this element of an array with index

# random_array = np.random.randint(1, 11, (3, 5))

# print("Original Array:")
# print(random_array)
# random_array[1, 2] = 99

# print("\nUpdated Array:")
# print(random_array)


n[:, 2] = [2, 4, 5]
n

array([[1, 2, 2, 4, 5],
       [2, 3, 4, 5, 6],
       [6, 7, 5, 9, 0]])

###Randomly generated arrays

-Numpy can create arrays filled with random numbers.
- To ensure  the reproducibility, you can set a seed using np.random.seed()

- Everytime  you run the code with np.random.seed(2),it will generate the exact same random numbers.

if you remove or change the seed valuses, the sequence of random numbers will be changed.

In [26]:
np.random.rand(3)

array([0.07901619, 0.89794823, 0.91822936])

In [30]:
np.random.seed(2)
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [33]:
np. random.seed(5)
np.random.rand(5, 2)


array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [35]:
np.random.randn(5, 2)

array([[-1.51117956,  0.64484751],
       [-0.98060789, -0.85685315],
       [-0.87187918, -0.42250793],
       [ 0.99643983,  0.71242127],
       [ 0.05914424, -0.36331088]])

In [36]:
np.random.seed(42)
np.random.randint(low=0, high=100, size=(5, 2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

### Element wise operations

In [38]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [39]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [40]:
#comparision operation
#you can  perform element - wise comparisons and create boolean arrays
a

array([0, 1, 2, 3, 4])

In [42]:
a >= 2

array([False, False,  True,  True,  True])

In [44]:
a > b

array([False, False, False, False, False])

In [46]:
#Summarizing
#Numpy provides functions for summarizing array of data
a

array([0, 1, 2, 3, 4])

In [47]:
#standard devistion
a. std()

1.4142135623730951

In [48]:
#minimum value of an array
a.min()

0

In [49]:
#max value of an array
a.max()

4

In [50]:
#sum of  elements of an array
a.sum()

10